apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "devpush.fullname" . }}-data
  labels:
    {{- include "devpush.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
