{{- if not .Values.env.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devpush.envSecretName" . }}
  labels:
    {{- include "devpush.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_HOSTNAME: {{ .Values.env.APP_HOSTNAME | quote }}
  DEPLOY_DOMAIN: {{ .Values.env.DEPLOY_DOMAIN | quote }}
  POSTGRES_DB: {{ .Values.env.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD | quote }}
  SECRET_KEY: {{ .Values.env.SECRET_KEY | quote }}
  ENCRYPTION_KEY: {{ .Values.env.ENCRYPTION_KEY | quote }}
  GITHUB_APP_ID: {{ .Values.env.GITHUB_APP_ID | quote }}
  GITHUB_APP_NAME: {{ .Values.env.GITHUB_APP_NAME | quote }}
  GITHUB_APP_PRIVATE_KEY: {{ .Values.env.GITHUB_APP_PRIVATE_KEY | quote }}
  GITHUB_APP_WEBHOOK_SECRET: {{ .Values.env.GITHUB_APP_WEBHOOK_SECRET | quote }}
  GITHUB_APP_CLIENT_ID: {{ .Values.env.GITHUB_APP_CLIENT_ID | quote }}
  GITHUB_APP_CLIENT_SECRET: {{ .Values.env.GITHUB_APP_CLIENT_SECRET | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.env.GOOGLE_CLIENT_ID | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.env.GOOGLE_CLIENT_SECRET | quote }}
  RESEND_API_KEY: {{ .Values.env.RESEND_API_KEY | quote }}
  SMTP_HOST: {{ .Values.env.SMTP_HOST | quote }}
  SMTP_PORT: {{ .Values.env.SMTP_PORT | quote }}
  SMTP_USERNAME: {{ .Values.env.SMTP_USERNAME | quote }}
  SMTP_PASSWORD: {{ .Values.env.SMTP_PASSWORD | quote }}
  EMAIL_SENDER_ADDRESS: {{ .Values.env.EMAIL_SENDER_ADDRESS | quote }}
  URL_SCHEME: {{ .Values.env.URL_SCHEME | quote }}
  ENV: {{ .Values.env.ENV | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  REDIS_URL: {{ .Values.env.REDIS_URL | quote }}
{{- end }}
