"""Adding tables for database support

Revision ID: 7249fc3a9d73
Revises: 31fe53421216
Create Date: 2026-01-05 08:55:24.650112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7249fc3a9d73'
down_revision: Union[str, Sequence[str], None] = '31fe53421216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('active', 'deleted', name='database_status'), nullable=False),
    sa.Column('size_limit_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_database_team_name')
    )
    op.create_index(op.f('ix_database_created_at'), 'database', ['created_at'], unique=False)
    op.create_index(op.f('ix_database_name'), 'database', ['name'], unique=False)
    op.create_index(op.f('ix_database_team_id'), 'database', ['team_id'], unique=False)
    op.create_index(op.f('ix_database_updated_at'), 'database', ['updated_at'], unique=False)
    op.create_table('project_database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('database_id', sa.String(length=32), nullable=False),
    sa.Column('environment_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['database.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'database_id', name='uq_project_database')
    )
    op.create_index(op.f('ix_project_database_database_id'), 'project_database', ['database_id'], unique=False)
    op.create_index(op.f('ix_project_database_project_id'), 'project_database', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_database_project_id'), table_name='project_database')
    op.drop_index(op.f('ix_project_database_database_id'), table_name='project_database')
    op.drop_table('project_database')
    op.drop_index(op.f('ix_database_updated_at'), table_name='database')
    op.drop_index(op.f('ix_database_team_id'), table_name='database')
    op.drop_index(op.f('ix_database_name'), table_name='database')
    op.drop_index(op.f('ix_database_created_at'), table_name='database')
    op.drop_table('database')
    # ### end Alembic commands ###
