"""Add image to deployment

Revision ID: 74bce1c629a6
Revises: f45484bf96b0
Create Date: 2026-01-31 11:32:07.510138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74bce1c629a6'
down_revision: Union[str, Sequence[str], None] = 'f45484bf96b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image')
    # ### end Alembic commands ###
