services:
  app:
    labels:
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=le
    volumes:
      - devpush-upload:/app/static/upload
      - devpush-traefik:/data/traefik

  traefik:
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=tcp://docker-proxy:2375
      - --providers.docker.watch=true
      - --providers.file.directory=/etc/traefik/dynamic_conf
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.le.acme.email=${LE_EMAIL}
      - --certificatesresolvers.le.acme.storage=/etc/traefik/dynamic_conf/acme.json
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - devpush-traefik:/etc/traefik/dynamic_conf

volumes:
  devpush-upload:
  devpush-traefik: