services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Docker/Dockerfile.app
    restart: always
    depends_on:
      - redis
      - docker-proxy
      - openresty
    networks:
      - default
      - internal
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - DOCKER_HOST=tcp://docker-proxy:2375

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
      - internal

  docker-proxy:
    container_name: docker-proxy
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      POST: 1
      EXEC: 1
      NETWORKS: 1
    networks:
      - internal

  openresty:
    image: openresty/openresty:alpine
    container_name: openresty
    env_file:
      - .env
    volumes:
      - ./Docker/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./Docker/ssl:/usr/local/openresty/nginx/conf/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
      - internal

  runner:
    image: runner
    build:
      context: ./Docker
      dockerfile: Dockerfile.runner
    profiles: ["build-only"]
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  app-runtime:

networks:
  default:
    name: app_default
  internal:
    name: app_internal
    internal: true