services:
  # app:
  #   volumes:
  #     - /srv/devpush/db:/data/db
  #     - /srv/devpush/traefik:/data/traefik
  #     - /srv/devpush/upload:/app/app/static/upload
  #   labels:
  #     - traefik.http.routers.app.entrypoints=websecure
  #     - traefik.http.routers.app.tls=true
  #     - traefik.http.routers.app.tls.certresolver=le
  #     - traefik.http.routers.app-static.entrypoints=websecure
  #     - traefik.http.routers.app-static.tls=true
  #     - traefik.http.routers.app-static.tls.certresolver=le
  
  api:
    labels:
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=le
    volumes:
      - /srv/devpush/traefik:/data/traefik
      - /srv/devpush/upload:/app/static/upload

  traefik:
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=tcp://docker-proxy:2375
      - --providers.docker.watch=true
      - --providers.file.directory=/etc/traefik/dynamic_conf
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.le.acme.email=${LE_EMAIL}
      - --certificatesresolvers.le.acme.storage=/etc/traefik/dynamic_conf/acme.json
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/devpush/traefik:/etc/traefik/dynamic_conf