services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Docker/Dockerfile.app
    restart: always
    depends_on:
      - redis
      - docker-proxy
    networks:
      - default
      - internal
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:////data/db/local.sqlite3
      - UPLOAD_DIR=/app/app/static/upload
      - TRAEFIK_CONFIG_DIR=/data/traefik
      - DOCKER_HOST=tcp://docker-proxy:2375
      - REDIS_URL=redis://redis:6379
    volumes:
      - /srv/devpush/db:/data/db
      - /srv/devpush/traefik:/data/traefik
      - /srv/devpush/upload:/app/app/static/upload
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.${BASE_DOMAIN}`)"
      - "traefik.http.routers.app.service=app@docker"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
      - "traefik.docker.network=devpush_default"
      - "traefik.http.middlewares.compress.compress=true"
      - "traefik.http.routers.app.middlewares=compress"

  api:
    container_name: api
    build:
      context: .
      dockerfile: Docker/Dockerfile.api
    restart: always
    depends_on:
      - redis
    networks:
      - default
      - internal
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.${BASE_DOMAIN}`)"
      - "traefik.http.routers.api.service=api@docker"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.docker.network=devpush_default"
      - "traefik.http.middlewares.compress.compress=true"
      - "traefik.http.routers.api.middlewares=compress"

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
      - internal

  docker-proxy:
    container_name: docker-proxy
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      POST: 1
      EXEC: 1
      NETWORKS: 1
    networks:
      - internal

  traefik:
    image: traefik:v3.3.2
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=tcp://docker-proxy:2375"
      - "--providers.docker.watch=true"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/devpush/traefik:/etc/traefik/dynamic_conf
    networks:
      - default
      - internal
    labels:
      - "traefik.enable=true"

  runner:
    image: runner
    build:
      context: ./Docker
      dockerfile: Dockerfile.runner
    profiles: ["build-only"]
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  devpush-db:
  devpush-traefik:
  devpush-upload:

networks:
  default:
    name: devpush_default
  internal:
    name: devpush_internal
    internal: true