---
- hosts: all
  vars:
    deploy_user: deploy
    app_dir: /home/deploy/devpush
    github_repo: "{{ github_repo }}"

  tasks:
    - name: Test GitHub SSH connection
      command: ssh -T git@github.com
      register: github_test
      failed_when: github_test.rc != 1
      changed_when: false

    - name: Display GitHub connection status
      debug:
        msg: "GitHub SSH connection successful"
      when: github_test.rc == 1

    - name: Clone repository
      git:
        repo: "{{ github_repo }}"
        dest: "{{ app_dir }}"
        update: yes
        force: yes

    - name: Copy .env file for app container
      ansible.builtin.copy:
        src: ../../../.env.prod
        dest: "{{ app_dir }}/.env"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: "0600"

    - name: ensure writable dirs
      file:
        path: "{{ item }}"
        state: directory
        owner: 1000
        group: 1000
        mode: "0755"
      loop:
        - /srv/devpush/traefik
        - /srv/devpush/upload

    - name: Prune builder cache
      command: docker builder prune -af
      when: docker_prune | default(false) | bool

    - name: Build images
      command: >
        docker compose -p devpush --profile build-only build
        {% if docker_no_cache | default(true) | bool %} --no-cache {% endif %}
      args:
        chdir: "{{ app_dir }}"

    - name: Start services
      command: docker compose -p devpush -f docker-compose.yml -f docker-compose.override.prod.yml up -d --pull always --remove-orphans
      args:
        chdir: "{{ app_dir }}"

    - name: Wait for database to be ready
      command: docker compose -p devpush exec pgsql pg_isready -U devpush-app
      args:
        chdir: "{{ app_dir }}"
      register: db_ready
      until: db_ready.rc == 0
      retries: 30
      delay: 2
      changed_when: false

    - name: Wait for app container to be ready
      wait_for:
        host: localhost
        port: 8000
        timeout: 60
      when: db_ready.rc == 0

    - name: Run database migrations
      command: docker compose -p devpush exec app uv run alembic upgrade head
      args:
        chdir: "{{ app_dir }}"
      when: db_ready.rc == 0