---
- hosts: all
  vars:
    deploy_user: deploy
    app_dir: /home/deploy/devpush
    github_repo: "{{ github_repo }}"

  tasks:
    - name: Clone repository
      git:
        repo: "https://github.com/hunvreus/devpush.git"
        dest: "{{ app_dir }}"
        update: yes
        force: yes

    - name: Copy .env file for app container
      ansible.builtin.copy:
        src: ../../../.env.prod
        dest: "{{ app_dir }}/.env"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: "0600"
    
    - name: Copy access list if present
      copy:
        src: ../../../access.json
        dest: /srv/devpush/access.json
        owner: 1000
        group: 1000
        mode: "0644"
      ignore_errors: yes

    - name: Ensure writable dirs
      file:
        path: "{{ item }}"
        state: directory
        owner: 1000
        group: 1000
        mode: "0755"
      loop:
        - /srv/devpush/traefik
        - /srv/devpush/upload

    - name: Prune builder cache
      command: docker builder prune -af
      when: docker_prune | default(false) | bool

    - name: Find Dockerfiles
      shell: find Docker/runner -name "Dockerfile.*" -exec basename {} \; | sed 's/Dockerfile\.//'
      args:
        chdir: "{{ app_dir }}"
      register: dockerfiles
      changed_when: false

    - name: Build runner images
      command: >
        docker build -f Docker/runner/Dockerfile.{{ item }} -t runner-{{ item }} ./Docker/runner
      args:
        chdir: "{{ app_dir }}"
      loop: "{{ dockerfiles.stdout_lines }}"

    - name: Start services
      command: docker compose -p devpush -f docker-compose.yml -f docker-compose.override.prod.yml up -d --pull always --remove-orphans
      args:
        chdir: "{{ app_dir }}"