services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
      args:
        APP_UID: ${SERVICE_UID:-1000}
        APP_GID: ${SERVICE_GID:-1000}
    entrypoint: /entrypoint.app.sh
    restart: always
    depends_on:
      - redis
      - pgsql
    networks:
      - default
      - internal
    env_file:
      - ${DATA_DIR:-../data}/.env
    environment:
      HOST_DATA_DIR: ${DATA_DIR:-../data}
    volumes:
      - ${DATA_DIR:-../data}:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`${APP_HOSTNAME}`)"
      - "traefik.http.routers.app.service=app@docker"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
      - "traefik.docker.network=devpush_default"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  worker-jobs:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
      args:
        APP_UID: ${SERVICE_UID:-1000}
        APP_GID: ${SERVICE_GID:-1000}
    entrypoint: /entrypoint.worker-jobs.sh
    restart: always
    stop_grace_period: ${JOB_TIMEOUT_SECONDS:-320}s
    depends_on:
      - redis
      - pgsql
    networks:
      - default
      - internal
      - runner
    env_file:
      - ${DATA_DIR:-../data}/.env
    environment:
      HOST_DATA_DIR: ${DATA_DIR:-../data}
    volumes:
      - ${DATA_DIR:-../data}:/data
    healthcheck:
      test: ["CMD", "uv", "run", "arq", "--check", "workers.jobs.WorkerSettings"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  worker-monitor:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
      args:
        APP_UID: ${SERVICE_UID:-1000}
        APP_GID: ${SERVICE_GID:-1000}
    entrypoint: /entrypoint.worker-monitor.sh
    restart: always
    depends_on:
      - redis
      - pgsql
    networks:
      - default
      - internal
      - runner
    env_file:
      - ${DATA_DIR:-../data}/.env
    environment:
      HOST_DATA_DIR: ${DATA_DIR:-../data}

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal

  docker-proxy:
    image: tecnativa/docker-socket-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINERS=1
      - INFO=1
      - SYSTEM=1
      - POST=1
      - EXEC=1
      - NETWORKS=1
      - DISABLE_IPV6=1
    networks:
      - internal

  traefik:
    image: traefik:v3.6.2
    restart: always
    depends_on:
      - docker-proxy
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=tcp://docker-proxy:2375"
      - "--providers.docker.watch=true"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
    networks:
      - default
      - internal
      - runner
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deployment-not-found.rule=HostRegexp(`^(.+)\\.${DEPLOY_DOMAIN}$`)"
      - "traefik.http.routers.deployment-not-found.entrypoints=web"
      - "traefik.http.routers.deployment-not-found.priority=1"
      - "traefik.http.routers.deployment-not-found.service=noop@internal"
      - "traefik.http.routers.deployment-not-found.middlewares=deployment-redirect"
      - "traefik.http.middlewares.deployment-redirect.redirectRegex.regex=^https?://([^/]+)"
      - "traefik.http.middlewares.deployment-redirect.redirectRegex.permanent=false"

  pgsql:
    image: postgres:16
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - internal
    environment:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      POSTGRES_DB: ${POSTGRES_DB:-devpush}
      POSTGRES_USER: ${POSTGRES_USER:-devpush-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
    volumes:
      - devpush-db:/var/lib/postgresql/data

  loki:
    image: grafana/loki:3.5.8
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - default
      - internal
    volumes:
      - loki-data:/loki
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3100/ready",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  alloy:
    image: grafana/alloy:v1.11.3
    command:
      - "run"
      - "/etc/alloy/config.alloy"
    restart: unless-stopped
    depends_on:
      - docker-proxy
      - loki
    networks:
      - default
      - internal
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ${APP_DIR:-..}/docker/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - alloy-data:/var/lib/alloy

volumes:
  devpush-db:
  loki-data:
  alloy-data:

networks:
  default:
    name: devpush_default
  internal:
    name: devpush_internal
    internal: true
  runner:
    name: devpush_runner
