services:
  app:
    build:
      dockerfile: docker/Dockerfile.app.dev
    entrypoint: /entrypoint.app.dev.sh
    labels:
      - traefik.http.routers.app.entrypoints=web
      - traefik.http.routers.app.priority=10
    volumes:
      - ${APP_DIR:-..}/app:/app
    environment:
      ENV: development
      UV_PROJECT_ENVIRONMENT: /opt/venv

  worker-arq:
    build:
      dockerfile: docker/Dockerfile.app.dev
    entrypoint: /entrypoint.worker-arq.dev.sh
    volumes:
      - ${APP_DIR:-..}/app:/app
    environment:
      ENV: development
      UV_PROJECT_ENVIRONMENT: /opt/venv

  worker-monitor:
    build:
      dockerfile: docker/Dockerfile.app.dev
    entrypoint: /entrypoint.worker-monitor.dev.sh
    volumes:
      - ${APP_DIR:-..}/app:/app
    environment:
      ENV: development
      UV_PROJECT_ENVIRONMENT: /opt/venv

  traefik:
    ports:
      - "80:80"
    volumes:
      - ${DATA_DIR:-../data}/traefik:/etc/traefik/dynamic_conf
    labels:
      - "traefik.http.middlewares.deployment-redirect.redirectRegex.replacement=http://${APP_HOSTNAME}/deployment-not-found/$$1"
