services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=tcp://docker-proxy:2375"
      - "--providers.docker.watch=true"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.le.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/etc/traefik/dynamic_conf/acme.json"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=route53"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - /srv/devpush/traefik:/etc/traefik/dynamic_conf
    labels:
      - "traefik.http.routers.cert-bootstrap.rule=Host(`${APP_HOSTNAME}`)"
      - "traefik.http.routers.cert-bootstrap.entrypoints=websecure"
      - "traefik.http.routers.cert-bootstrap.tls=true"
      - "traefik.http.routers.cert-bootstrap.tls.certresolver=le"
      - "traefik.http.routers.cert-bootstrap.priority=1"
      - "traefik.http.routers.cert-bootstrap.service=noop@internal"
      - "traefik.http.routers.cert-bootstrap.tls.domains[0].main=${DEPLOY_DOMAIN}"
      - "traefik.http.routers.cert-bootstrap.tls.domains[0].sans=*.${DEPLOY_DOMAIN}"
      - "traefik.http.routers.cert-bootstrap.tls.domains[1].main=${APP_HOSTNAME}"


