[project]
name = "devpush-api"
version = "0.1.0"
description = "API for devpush"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "fastapi-cli>=0.0.7",
    "jinja2>=3.1.6",
    "redis>=6.1.0",
    "uvicorn>=0.34.2",
]
